### ISSUE TITLE
Don't commit usernames and passwords!!

### ISSUE THREAD

**Issue by killertilapia** [jeezasalise/Salise-day5-web#1]
https://github.com/jeezasalise/Salise-day5-web/blob/e87c44921934bc5ef503d5d176d05b0e4d76e682/FlaskwithMongo/app.py#L11

Don't commit usernames and passwords!! 

Repos in Github are public. Anyone can read your code and see your usernames and passwords.

Use something like os.getenv() to inject usernames and passwords.

https://www.geeksforgeeks.org/python-os-getenv-method/

**Comment by jeezasalise** [comment]
#4 Injected the URI and changed the username and password.
