### ISSUE TITLE
What does this function do?

### ISSUE THREAD

**Issue by killertilapia** [jeezasalise/Salise-day5-web#2]
https://github.com/jeezasalise/Salise-day5-web/blob/e87c44921934bc5ef503d5d176d05b0e4d76e682/FlaskwithMongo/app.py#L78

What does this function do? That's would be my question? `/action3` isn't helpful as a function name. A better more descriptive name would be better. 

Remember, you're not writing code only for yourself but also for others.

**Comment by jeezasalise** [comment]
#3 PR accepted.
